version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_db:/data/db
    ports:
      - 2717:27017

  api:
    container_name: api_container
    build: .
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      # DB_USER=DATABASE USER
      # DB_PASS=DATABASE USER PASSWORD
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: myDB1
      NAME: SamirHusain
    depends_on:
      - mongo_db

  redis:
    container_name: redis_container
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379

volumes:
  mongo_db: {}
